// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-team-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-team-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddTeams mocks base method.
func (m *MockRepo) AddTeams(arg0 []models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeams", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeams indicates an expected call of AddTeams.
func (mr *MockRepoMockRecorder) AddTeams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeams", reflect.TypeOf((*MockRepo)(nil).AddTeams), arg0)
}

// DescribeTeam mocks base method.
func (m *MockRepo) DescribeTeam(arg0 uint64) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeTeam", arg0)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTeam indicates an expected call of DescribeTeam.
func (mr *MockRepoMockRecorder) DescribeTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTeam", reflect.TypeOf((*MockRepo)(nil).DescribeTeam), arg0)
}

// ListTeams mocks base method.
func (m *MockRepo) ListTeams(arg0, arg1 uint64) ([]models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", arg0, arg1)
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeams indicates an expected call of ListTeams.
func (mr *MockRepoMockRecorder) ListTeams(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*MockRepo)(nil).ListTeams), arg0, arg1)
}
