// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/ocp-team-api/ocp-team-api.proto

package ocp_team_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTeamV1Request_Type int32

const (
	SearchTeamV1Request_PLAIN  SearchTeamV1Request_Type = 0
	SearchTeamV1Request_PHRASE SearchTeamV1Request_Type = 1
)

// Enum value maps for SearchTeamV1Request_Type.
var (
	SearchTeamV1Request_Type_name = map[int32]string{
		0: "PLAIN",
		1: "PHRASE",
	}
	SearchTeamV1Request_Type_value = map[string]int32{
		"PLAIN":  0,
		"PHRASE": 1,
	}
)

func (x SearchTeamV1Request_Type) Enum() *SearchTeamV1Request_Type {
	p := new(SearchTeamV1Request_Type)
	*p = x
	return p
}

func (x SearchTeamV1Request_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTeamV1Request_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ocp_team_api_ocp_team_api_proto_enumTypes[0].Descriptor()
}

func (SearchTeamV1Request_Type) Type() protoreflect.EnumType {
	return &file_api_ocp_team_api_ocp_team_api_proto_enumTypes[0]
}

func (x SearchTeamV1Request_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTeamV1Request_Type.Descriptor instead.
func (SearchTeamV1Request_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{12, 0}
}

type CreateTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateTeamV1Request) Reset() {
	*x = CreateTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamV1Request) ProtoMessage() {}

func (x *CreateTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamV1Request.ProtoReflect.Descriptor instead.
func (*CreateTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamV1Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamV1Request) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTeamV1Response) Reset() {
	*x = CreateTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamV1Response) ProtoMessage() {}

func (x *CreateTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamV1Response.ProtoReflect.Descriptor instead.
func (*CreateTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamV1Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MultiCreateTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams []*CreateTeamV1Request `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *MultiCreateTeamV1Request) Reset() {
	*x = MultiCreateTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateTeamV1Request) ProtoMessage() {}

func (x *MultiCreateTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateTeamV1Request.ProtoReflect.Descriptor instead.
func (*MultiCreateTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{2}
}

func (x *MultiCreateTeamV1Request) GetTeams() []*CreateTeamV1Request {
	if x != nil {
		return x.Teams
	}
	return nil
}

type MultiCreateTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MultiCreateTeamV1Response) Reset() {
	*x = MultiCreateTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateTeamV1Response) ProtoMessage() {}

func (x *MultiCreateTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateTeamV1Response.ProtoReflect.Descriptor instead.
func (*MultiCreateTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{3}
}

func (x *MultiCreateTeamV1Response) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTeamV1Request) Reset() {
	*x = GetTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamV1Request) ProtoMessage() {}

func (x *GetTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamV1Request.ProtoReflect.Descriptor instead.
func (*GetTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
}

func (x *GetTeamV1Response) Reset() {
	*x = GetTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamV1Response) ProtoMessage() {}

func (x *GetTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamV1Response.ProtoReflect.Descriptor instead.
func (*GetTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeamV1Response) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type ListTeamsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListTeamsV1Request) Reset() {
	*x = ListTeamsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeamsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsV1Request) ProtoMessage() {}

func (x *ListTeamsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsV1Request.ProtoReflect.Descriptor instead.
func (*ListTeamsV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListTeamsV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTeamsV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTeamsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint64  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Teams []*Team `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *ListTeamsV1Response) Reset() {
	*x = ListTeamsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeamsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsV1Response) ProtoMessage() {}

func (x *ListTeamsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsV1Response.ProtoReflect.Descriptor instead.
func (*ListTeamsV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeamsV1Response) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTeamsV1Response) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type RemoveTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveTeamV1Request) Reset() {
	*x = RemoveTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamV1Request) ProtoMessage() {}

func (x *RemoveTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamV1Request.ProtoReflect.Descriptor instead.
func (*RemoveTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveTeamV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveTeamV1Response) Reset() {
	*x = RemoveTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamV1Response) ProtoMessage() {}

func (x *RemoveTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamV1Response.ProtoReflect.Descriptor instead.
func (*RemoveTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{9}
}

type UpdateTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
}

func (x *UpdateTeamV1Request) Reset() {
	*x = UpdateTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamV1Request) ProtoMessage() {}

func (x *UpdateTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamV1Request.ProtoReflect.Descriptor instead.
func (*UpdateTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTeamV1Request) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type UpdateTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTeamV1Response) Reset() {
	*x = UpdateTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamV1Response) ProtoMessage() {}

func (x *UpdateTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamV1Response.ProtoReflect.Descriptor instead.
func (*UpdateTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{11}
}

type SearchTeamV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  SearchTeamV1Request_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ocp.team.api.SearchTeamV1Request_Type" json:"type,omitempty"`
	Query string                   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchTeamV1Request) Reset() {
	*x = SearchTeamV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTeamV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeamV1Request) ProtoMessage() {}

func (x *SearchTeamV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeamV1Request.ProtoReflect.Descriptor instead.
func (*SearchTeamV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{12}
}

func (x *SearchTeamV1Request) GetType() SearchTeamV1Request_Type {
	if x != nil {
		return x.Type
	}
	return SearchTeamV1Request_PLAIN
}

func (x *SearchTeamV1Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchTeamV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams []*Team `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *SearchTeamV1Response) Reset() {
	*x = SearchTeamV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTeamV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeamV1Response) ProtoMessage() {}

func (x *SearchTeamV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeamV1Response.ProtoReflect.Descriptor instead.
func (*SearchTeamV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{13}
}

func (x *SearchTeamV1Response) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_team_api_ocp_team_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP(), []int{14}
}

func (x *Team) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_ocp_team_api_ocp_team_api_proto protoreflect.FileDescriptor

var file_api_ocp_team_api_ocp_team_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e,
	0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e,
	0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04,
	0x10, 0x03, 0x18, 0x64, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x18, 0x90, 0x4e, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d,
	0x0a, 0x18, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x08, 0xfa, 0x42,
	0x05, 0x92, 0x01, 0x02, 0x08, 0x02, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x22, 0x2d, 0x0a,
	0x19, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d,
	0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x22, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x09, 0xfa, 0x42, 0x06,
	0x32, 0x04, 0x18, 0x64, 0x20, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x13,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x74,
	0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x04, 0x74,
	0x65, 0x61, 0x6d, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x13,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01,
	0x02, 0x10, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x49, 0x4e,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x48, 0x52, 0x41, 0x53, 0x45, 0x10, 0x01, 0x22, 0x40,
	0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x22, 0x6a, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x03, 0x18, 0x64, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2a, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x18, 0x90, 0x4e, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x9f, 0x06, 0x0a,
	0x0a, 0x4f, 0x63, 0x70, 0x54, 0x65, 0x61, 0x6d, 0x41, 0x70, 0x69, 0x12, 0x6b, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x85, 0x01, 0x0a, 0x11, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x26,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61,
	0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x61,
	0x6d, 0x73, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a,
	0x12, 0x64, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x1e, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x61, 0x6d,
	0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x65, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x56, 0x31, 0x12, 0x20, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65,
	0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0b, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x6d, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x21, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x2a, 0x0e, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x6b, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x1a, 0x09, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x73, 0x0a, 0x0d, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x65, 0x61, 0x6d, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x3a, 0x01, 0x2a, 0x42, 0x3e,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f,
	0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2d, 0x61, 0x70,
	0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_team_api_ocp_team_api_proto_rawDescOnce sync.Once
	file_api_ocp_team_api_ocp_team_api_proto_rawDescData = file_api_ocp_team_api_ocp_team_api_proto_rawDesc
)

func file_api_ocp_team_api_ocp_team_api_proto_rawDescGZIP() []byte {
	file_api_ocp_team_api_ocp_team_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_team_api_ocp_team_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_team_api_ocp_team_api_proto_rawDescData)
	})
	return file_api_ocp_team_api_ocp_team_api_proto_rawDescData
}

var file_api_ocp_team_api_ocp_team_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ocp_team_api_ocp_team_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_ocp_team_api_ocp_team_api_proto_goTypes = []interface{}{
	(SearchTeamV1Request_Type)(0),     // 0: ocp.team.api.SearchTeamV1Request.Type
	(*CreateTeamV1Request)(nil),       // 1: ocp.team.api.CreateTeamV1Request
	(*CreateTeamV1Response)(nil),      // 2: ocp.team.api.CreateTeamV1Response
	(*MultiCreateTeamV1Request)(nil),  // 3: ocp.team.api.MultiCreateTeamV1Request
	(*MultiCreateTeamV1Response)(nil), // 4: ocp.team.api.MultiCreateTeamV1Response
	(*GetTeamV1Request)(nil),          // 5: ocp.team.api.GetTeamV1Request
	(*GetTeamV1Response)(nil),         // 6: ocp.team.api.GetTeamV1Response
	(*ListTeamsV1Request)(nil),        // 7: ocp.team.api.ListTeamsV1Request
	(*ListTeamsV1Response)(nil),       // 8: ocp.team.api.ListTeamsV1Response
	(*RemoveTeamV1Request)(nil),       // 9: ocp.team.api.RemoveTeamV1Request
	(*RemoveTeamV1Response)(nil),      // 10: ocp.team.api.RemoveTeamV1Response
	(*UpdateTeamV1Request)(nil),       // 11: ocp.team.api.UpdateTeamV1Request
	(*UpdateTeamV1Response)(nil),      // 12: ocp.team.api.UpdateTeamV1Response
	(*SearchTeamV1Request)(nil),       // 13: ocp.team.api.SearchTeamV1Request
	(*SearchTeamV1Response)(nil),      // 14: ocp.team.api.SearchTeamV1Response
	(*Team)(nil),                      // 15: ocp.team.api.Team
}
var file_api_ocp_team_api_ocp_team_api_proto_depIdxs = []int32{
	1,  // 0: ocp.team.api.MultiCreateTeamV1Request.teams:type_name -> ocp.team.api.CreateTeamV1Request
	15, // 1: ocp.team.api.GetTeamV1Response.team:type_name -> ocp.team.api.Team
	15, // 2: ocp.team.api.ListTeamsV1Response.teams:type_name -> ocp.team.api.Team
	15, // 3: ocp.team.api.UpdateTeamV1Request.team:type_name -> ocp.team.api.Team
	0,  // 4: ocp.team.api.SearchTeamV1Request.type:type_name -> ocp.team.api.SearchTeamV1Request.Type
	15, // 5: ocp.team.api.SearchTeamV1Response.teams:type_name -> ocp.team.api.Team
	1,  // 6: ocp.team.api.OcpTeamApi.CreateTeamV1:input_type -> ocp.team.api.CreateTeamV1Request
	3,  // 7: ocp.team.api.OcpTeamApi.MultiCreateTeamV1:input_type -> ocp.team.api.MultiCreateTeamV1Request
	5,  // 8: ocp.team.api.OcpTeamApi.GetTeamV1:input_type -> ocp.team.api.GetTeamV1Request
	7,  // 9: ocp.team.api.OcpTeamApi.ListTeamsV1:input_type -> ocp.team.api.ListTeamsV1Request
	9,  // 10: ocp.team.api.OcpTeamApi.RemoveTeamV1:input_type -> ocp.team.api.RemoveTeamV1Request
	11, // 11: ocp.team.api.OcpTeamApi.UpdateTeamV1:input_type -> ocp.team.api.UpdateTeamV1Request
	13, // 12: ocp.team.api.OcpTeamApi.SearchTeamsV1:input_type -> ocp.team.api.SearchTeamV1Request
	2,  // 13: ocp.team.api.OcpTeamApi.CreateTeamV1:output_type -> ocp.team.api.CreateTeamV1Response
	4,  // 14: ocp.team.api.OcpTeamApi.MultiCreateTeamV1:output_type -> ocp.team.api.MultiCreateTeamV1Response
	6,  // 15: ocp.team.api.OcpTeamApi.GetTeamV1:output_type -> ocp.team.api.GetTeamV1Response
	8,  // 16: ocp.team.api.OcpTeamApi.ListTeamsV1:output_type -> ocp.team.api.ListTeamsV1Response
	10, // 17: ocp.team.api.OcpTeamApi.RemoveTeamV1:output_type -> ocp.team.api.RemoveTeamV1Response
	12, // 18: ocp.team.api.OcpTeamApi.UpdateTeamV1:output_type -> ocp.team.api.UpdateTeamV1Response
	14, // 19: ocp.team.api.OcpTeamApi.SearchTeamsV1:output_type -> ocp.team.api.SearchTeamV1Response
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_ocp_team_api_ocp_team_api_proto_init() }
func file_api_ocp_team_api_ocp_team_api_proto_init() {
	if File_api_ocp_team_api_ocp_team_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeamsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeamsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTeamV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTeamV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_team_api_ocp_team_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_team_api_ocp_team_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_team_api_ocp_team_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_team_api_ocp_team_api_proto_depIdxs,
		EnumInfos:         file_api_ocp_team_api_ocp_team_api_proto_enumTypes,
		MessageInfos:      file_api_ocp_team_api_ocp_team_api_proto_msgTypes,
	}.Build()
	File_api_ocp_team_api_ocp_team_api_proto = out.File
	file_api_ocp_team_api_ocp_team_api_proto_rawDesc = nil
	file_api_ocp_team_api_ocp_team_api_proto_goTypes = nil
	file_api_ocp_team_api_ocp_team_api_proto_depIdxs = nil
}
